export enum GameCategory {
  Featured = 'featured',
  Football = 'football',
  Tennis = 'tennis',
  Volleyball = 'volleyball',
  NFL = 'nfl',
  Baseball = 'baseball',
  MMA = 'mma',
  Hokey = 'hokey',
  Cricket = 'cricket',
  CSGO = 'csgo',
  Dota = 'dota',
  Handball = 'handball',
  Darts = 'darts',
  Golf = 'golf',
  Snooker = 'snooker',
  Cycling = 'cycling',
  Netball = 'netball',
  Basketball = 'basketball',
  Futsal = 'futsal',
  Surfing = 'surfing',
  Chess = 'chess',
}

export const gameCategoryNames: Record<GameCategory, string> = {
  [GameCategory.Featured]: 'Featured',
  [GameCategory.Football]: 'Soccer',
  [GameCategory.Basketball]: 'Basketball',
  [GameCategory.Tennis]: 'Tennis',
  [GameCategory.Volleyball]: 'Volleyball',
  [GameCategory.Baseball]: 'Baseball',
  [GameCategory.Handball]: 'Handball',
  [GameCategory.Cricket]: 'Cricket',
  [GameCategory.MMA]: 'MMA',
  [GameCategory.Snooker]: 'Snooker',
  [GameCategory.Darts]: 'Darts',
  [GameCategory.Golf]: 'Golf',
  [GameCategory.Cycling]: 'Cycling',
  [GameCategory.Chess]: 'Chess',
  [GameCategory.Dota]: 'Dota 2',
  [GameCategory.Hokey]: 'Hokey',
  [GameCategory.Netball]: 'Netball',
  [GameCategory.CSGO]: 'CS:GO',
  [GameCategory.Futsal]: 'Futsal',
  [GameCategory.NFL]: 'Football',
  [GameCategory.Surfing]: 'Surfing',
};
