export enum ApiPaths {
  AuthLogin = '/api/v1/auth/sign_in',
  AuthSignUp = '/api/v1/auth/sign_up',
  AuthRefresh = '/api/v1/auth/refresh',
  AuthCurencyChange = '/api/v1/auth/change_currency',
  AuthGetGuestToken = '/api/v1/auth/guest',
  AuthGetMe = '/api/v1/notifier/users/me',
  AuthGetRanks = '/api/v1/affiliate/ranks',
  AuthGetMyAffiliates = '/api/v1/affiliate/users_me',
  ChatAddMessage = '/api/v1/chat/messages',
  ChatTip = '/api/v1/payments/tipping',
  ChatRain = '/api/v1/chat/money_rain',
  ChatUsersOnline = '/api/v1/chat/users_online',
  ChatGetUser = '/api/v1/notifier/users/',
  UserFind = '/api/v1/notifier/users/find',
  AffiliateGetAccounts = '/api/v1/transactions/my_accounts ',
  AuthLoginMetamask = '/api/v1/notifier/metamask_sign_in',
  AuthMetamaskPreSigned = '/api/v1/notifier/metamask_pre_signed',
  AuthSignUpMetamask = '/api/v1/notifier/metamask_sign_up',
  OAuth2Google = '/api/v1/notifier/oauth2/google/authorization',
  OAuth2Facebook = '/api/v1/notifier/oauth2/facebook/authorization',
  OAuthSignup = '/api/v1/notifier/oauth2_signup',
  CheckLoginExists = '/api/v1/notifier/check_login_exists',
  RainMinAmount = '/api/v1/chat/money_rain/minimum_amount',
  GetRates = '/api/v1/rates/rates',
  AuthLoginTelegram = '/api/v1/notifier/telegram_sign_in',
  AuthSignUpTelegram = '/api/v1/notifier/telegram_sign_up',
  MessageDownload = '/api/v1/chat/messages/download',
  ProfileDeposit = '/api/v1/payments/deposit',
  KYCCreate = '/api/v1/notifier/kyc/create',
  KYCUpdate = '/api/v1/notifier/kyc/update',
  KYC = '/api/v1/notifier/kyc/',
  SportsBet = '/api/v1/affiliate/sports_bets',
  Withdraw = '/api/v1/payments/withdraw',
  TransactionAll = '/api/v1/transactions/my',
  KYCProofOfAddress = '/api/v1/notifier/kyc/address_file',
  KYCSourceOfFunds = '/api/v1/notifier/kyc/funds_file',
  KYCIdentityBack = '/api/v1/notifier/kyc/identity_back_file',
  KYCIdentityFront = '/api/v1/notifier/kyc/identity_front_file',
  GameToken = '/api/v1/auth/game_token',
  ProfileAvatarSet = '/api/v1/notifier/user/profile/avatar',
  ProfileAvatarRemove = '/api/v1/notifier/user/profile/avatar',
  LatestBets = '/api/v1/transactions/latest_bets',
  BcCurrency = '/api/v1/notifier/set_bc_currency',
  ChangePassword = '/api/v1/notifier/change_password',
  ChangeEmail = '/api/v1/notifier/change_email',
  PreCheck = '/api/v1/payments/withdrawal/pre_check',
  TWOFA = '/api/v1/notifier/gen_qr_code',
  TWOFAACTIVATE = '/api/v1/notifier/confirm_qr_code',
  TWOFADEACTIVATE = '/api/v1/notifier/remove_2fa',
  AffiliateUsersAccounts = '/api/v1/affiliate/users/accounts',
  AffiliateReferralList = '/api/v1/affiliate/referral_list',
  AffiliateCampaignList = '/api/v1/affiliate/campaigns',
  AffiliateCreateCampaign = '/api/v1/affiliate/campaigns',
  AffiliateWithdrawTransfer = '/api/v1/affiliate/transfer',
  BONUSES = '/api/v1/bonus/eligible',
  CLAIMBONUS = '/api/v1/bonus/activate',
  CANCELBONUS = '/api/v1/bonus/cancel',
}

export enum ApiCMSPaths {
  CMSGetGames = 'items/games',
  CMSGetBanners = 'items/banners',
  CMSGetRecommendationsGames = 'items/recommendations_games',
  CMSGetAssets = 'items/assets',
}

export const backendBalancePrecision = 1e20;
